/// Flutter icons BackIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BackIcons
///      fonts:
///       - asset: fonts/BackIcons.ttf
///
/// 
///
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class BackIcons {
  BackIcons._();

  static const _kFontFam = 'BackIcons';
  static const String? _kFontPkg = null;

  static const IconData circle_arrow = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
