/// Flutter icons BottNavIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BottNavIcon
///      fonts:
///       - asset: fonts/BottNavIcon.ttf
///
/// 
///
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class BottNavIcon {
  BottNavIcon._();

  static const _kFontFam = 'BottNavIcon';
  static const String? _kFontPkg = null;

  static const IconData pdrb_bottnav_icon = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ipm_bottnav_icon = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_bottnav_icon_2 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sensus_bottnav_icon = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
