/// Flutter icons BottNavIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BottNavIcons
///      fonts:
///       - asset: fonts/BottNavIcons.ttf
///
///
///
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class BottNavIcons {
  BottNavIcons._();

  static const _kFontFam = 'BottNavIcons';
  static const String? _kFontPkg = null;

  static const IconData home =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_group =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData positive_dynamics =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
