/// Flutter icons AboutIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AboutIcons
///      fonts:
///       - asset: fonts/AboutIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AboutIcons {
  AboutIcons._();

  static const _kFontFam = 'AboutIcons';
  static const String? _kFontPkg = null;

  static const IconData frame = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData framebrowser = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData framecube = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
